In [1]:
import numpy as np
import pandas as pd

In [2]:
# load data
booze = pd.read_csv("drinks.csv")

In [3]:
booze[:10]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
5,Antigua & Barbuda,102,128,45,4.9
6,Argentina,193,25,221,8.3
7,Armenia,21,179,11,3.8
8,Australia,261,72,212,10.4
9,Austria,279,75,191,9.7

In [4]:
# Get the largest of each type
booze.apply(lambda x: x.max())

country                         Zimbabwe
beer_servings                        376
spirit_servings                      438
wine_servings                        370
total_litres_of_pure_alcohol        14.4
dtype: object

In [5]:
# What is the favorite drink of a country?
def favorite_drink(x):
    # Removes countries that have 0 alcohol consumption
    if (x[4] == 0):
        return "Teetotal"
    # The columns method is an array-like object.
    # This slices columns 1-3 (beer_servings - wine_servings) and applies the pandas max() method
    # replace() slices the '_serving' off the column header to provide which drink the country prefers
    return booze.columns[np.where(x == x[1:3].max())][0].replace('_servings', '')

In [9]:
# Get favorites
# axis is required and refers to the column to reference
faves = booze.apply(favorite_drink, axis=1)

In [15]:
# Concatenate to make a new dataframe
# default assumes that we want to concat based on columns, so axis must be provided again
# pd.concat((booze, faves), axis=1)

# this can be passed as a dataframe, to create a new dataframe
# this adds a new column header for the country's favorite alcohol called 'favorite'
newbooze = pd.concat((booze, pd.DataFrame({'favorite': faves})), axis=1)

In [16]:
# With the new dataframe, you can now select based on the new column
# This selects countries that prefer beer as their favorite alcohol
newbooze[newbooze.favorite == 'beer']

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,favorite
2,Algeria,25,0,14,0.7,beer
3,Andorra,245,138,312,12.4,beer
4,Angola,217,57,45,5.9,beer
6,Argentina,193,25,221,8.3,beer
8,Australia,261,72,212,10.4,beer
9,Austria,279,75,191,9.7,beer
16,Belgium,295,84,212,10.5,beer
17,Belize,263,114,8,6.8,beer
18,Benin,34,4,13,1.1,beer
19,Bhutan,23,0,0,0.4,beer
20,Bolivia,167,41,8,3.8,beer
22,Botswana,173,35,35,5.4,beer
23,Brazil,245,145,16,7.2,beer
24,Brunei,31,2,1,0.6,beer
26,Burkina Faso,25,7,7,4.3,beer
27,Burundi,88,0,0,6.3,beer
28,Cote d'Ivoire,37,1,7,4.0,beer
29,Cabo Verde,144,56,16,4.0,beer
31,Cameroon,147,1,4,5.8,beer
32,Canada,240,122,100,8.2,beer
33,Central African Republic,17,2,1,1.8,beer
34,Chad,15,1,1,0.4,beer
35,Chile,130,124,172,7.6,beer
37,Colombia,159,76,3,4.2,beer
39,Congo,76,1,9,1.7,beer
41,Costa Rica,149,87,11,4.4,beer
42,Croatia,230,87,254,10.2,beer
44,Cyprus,192,154,113,8.2,beer
45,Czech Republic,361,170,134,11.8,beer
47,DR Congo,32,3,1,2.3,beer
...,...,...,...,...,...,...
150,Senegal,9,1,7,0.3,beer
151,Serbia,283,131,127,9.6,beer
152,Seychelles,157,25,51,4.1,beer
153,Sierra Leone,25,3,2,6.7,beer
154,Singapore,60,12,11,1.5,beer
156,Slovenia,270,51,276,10.6,beer
157,Solomon Islands,56,11,1,1.2,beer
159,South Africa,225,76,81,8.2,beer
160,Spain,284,157,112,10.0,beer
164,Swaziland,90,2,2,4.7,beer
165,Sweden,152,60,186,7.2,beer
166,Switzerland,185,100,280,10.2,beer
170,Macedonia,106,27,86,3.9,beer
171,Timor-Leste,1,1,4,0.1,beer
172,Togo,36,2,19,1.3,beer
173,Tonga,36,21,5,1.1,beer
174,Trinidad & Tobago,197,156,7,6.4,beer
175,Tunisia,51,3,20,1.3,beer
176,Turkey,51,22,7,1.4,beer
179,Uganda,45,9,0,8.3,beer
182,United Kingdom,219,126,195,10.4,beer
183,Tanzania,36,6,1,5.7,beer
184,USA,249,158,84,8.7,beer
185,Uruguay,115,35,220,6.6,beer
187,Vanuatu,21,18,11,0.9,beer
188,Venezuela,333,100,3,7.7,beer
189,Vietnam,111,2,1,2.0,beer
190,Yemen,6,0,0,0.1,beer
191,Zambia,32,19,4,2.5,beer
192,Zimbabwe,64,18,4,4.7,beer